// GOAL: Configure Vite for the React application and local Hono API.
// RESPONSIBILITY: React transforms plus a development-only API bridge.
// DOES NOT: Move market logic into Vite or expose Delta secrets to the browser.
import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { app } from "./server/app";

// Bridge Hono into Vite's Node development middleware without another server process.
function honoDevServer(): Plugin {
  // Return a Vite plugin object with the one hook required by this MVP.
  return {
    name: "hono-dev-server",
    configureServer(server) {
      // Register before the SPA fallback so /api/* reaches Hono first.
      server.middlewares.use(async (request, response, next) => {
        // Leave non-API browser assets to Vite's normal middleware chain.
        if (!request.url?.startsWith("/api/")) return next();

        try {
          // Build a standard Fetch Request from Vite's incoming Node request.
          const url = new URL(request.url, "http://localhost");
          const fetchRequest = new Request(url, {
            method: request.method ?? "GET",
          });

          // Let Hono handle routing, provider calls, and JSON serialization.
          const fetchResponse = await app.fetch(fetchRequest);

          // Copy the Hono status code into the Node response.
          response.statusCode = fetchResponse.status;

          // Copy response headers back to Vite's HTTP response.
          fetchResponse.headers.forEach((value, key) => {
            response.setHeader(key, value);
          });

          // Convert the Fetch body into bytes because the MVP exposes JSON GET endpoints.
          const body = Buffer.from(await fetchResponse.arrayBuffer());

          // Finish the HTTP response with the Hono-generated bytes.
          response.end(body);
        } catch (error) {
          // Log development failures while keeping the browser response generic.
          console.error("Hono dev server error", error);
          response.statusCode = 500;
          response.end(
            JSON.stringify({
              success: false,
              error: "Development API failure",
            }),
          );
        }
      });
    },
  };
}

// Export the Vite configuration used by development and production builds.
export default defineConfig({
  plugins: [react(), honoDevServer()],
});
